#
# ███╗░░░███╗███████╗██████╗░██╗███████╗██╗░░░██╗░█████╗░██╗░░░░░░██╗░░░░░░░██╗███████╗░█████╗░██████╗░░█████╗░███╗░░██╗░██████╗
# ████╗░████║██╔════╝██╔══██╗██║██╔════╝██║░░░██║██╔══██╗██║░░░░░░██║░░██╗░░██║██╔════╝██╔══██╗██╔══██╗██╔══██╗████╗░██║██╔════╝
# ██╔████╔██║█████╗░░██║░░██║██║█████╗░░╚██╗░██╔╝███████║██║░░░░░░╚██╗████╗██╔╝█████╗░░███████║██████╔╝██║░░██║██╔██╗██║╚█████╗░
# █║╚██╔╝██║██╔══╝░░██║░░██║██║██╔══╝░░░╚████╔╝░██╔══██║██║░░░░░░░████╔═████║░██╔══╝░░██╔══██║██╔═══╝░██║░░██║██║╚████║░╚═══██╗
# ██║░╚═╝░██║███████╗██████╔╝██║███████╗░░╚██╔╝░░██║░░██║███████╗░░╚██╔╝░╚██╔╝░███████╗██║░░██║██║░░░░░╚█████╔╝██║░╚███║██████╔╝
# ╚═╝░░░░░╚═╝╚══════╝╚═════╝░╚═╝╚══════╝░░░╚═╝░░░╚═╝░░╚═╝╚══════╝░░░╚═╝░░░╚═╝░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░░╚════╝░╚═╝░░╚══╝╚═════╝░
#
# DEV By @RyzeProjects
# Version 1.0
# For suggestion or if you run into a problem, please contact me on Telegram @xoxRyze!
# This is the config.yml
#